### ISSUE TITLE
Спрячьте ключи из паблика репозитория или сам репозиторий. Не секьюрно как то ) 

### ISSUE THREAD

**Issue by UstyuzhaninAV** [KochergaClub/core#14]
https://github.com/KochergaClub/core/blob/84a4babb52cef5c5d82a86463ce9eae713d9fc94/ops/values/core/prod/main.yaml#L12

**Comment by berekuk** [comment]
Это ключ, предназначенный для браузеров, для отрисовки виджета google-карт, его не нужно прятать.
(Сейчас не используется, но мб будет использоваться в будущем снова).
